import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime

# -----------------------------------------------------------------------------
# 1. Page Configuration
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="Aadhar Enrolment Monitoring System (AEMS)",
    page_icon="🇮🇳",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# CSS to hide default Streamlit footer and menu for a purely official look
hide_streamlit_style = """
<style>
#MainMenu {visibility: hidden;}
footer {visibility: hidden;}
</style>
"""
st.markdown(hide_streamlit_style, unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# 2. Data Loading & Caching
# -----------------------------------------------------------------------------
@st.cache_data
def load_data():
    files = [
        'api_data_aadhar_enrolment_0_500000.csv',
        'api_data_aadhar_enrolment_500000_1000000.csv',
        'api_data_aadhar_enrolment_1000000_1006029.csv'
    ]
    
    dfs = []
    for f in files:
        try:
            df = pd.read_csv(f)
            dfs.append(df)
        except FileNotFoundError:
            st.error(f"File not found: {f}. Please ensure all CSVs are in the directory.")
            return None

    df = pd.concat(dfs, ignore_index=True)
    
    # Preprocessing
    df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y', errors='coerce')
    df['Total Enrolment'] = df['age_0_5'] + df['age_5_17'] + df['age_18_greater']
    
    # Calculate Ratios
    df['Child_Ratio'] = df['age_0_5'] / df['Total Enrolment']
    
    return df

df = load_data()

if df is None:
    st.stop()

# -----------------------------------------------------------------------------
# 3. Main Dashboard Header (Moved Up for Top Navigation Flow)
# -----------------------------------------------------------------------------
st.title("🏛️ Aadhar Enrolment Monitoring System (AEMS)")
# Updated heading to specifically relate to the strategic insight provided
st.markdown("### Strategic Intelligence Module: Targeting Demographic Deficits in Meghalaya & North-East Region")

# Module Information Section (Visible by Default - No longer collapsed)
st.markdown("#### ℹ️ About this Module: Strategic Utility & Statistical Methodology")

st.markdown("""
### **1. Strategic Utility & Operational Roadmap**

**How this Module Drives Governance:**
This dashboard transforms raw enrolment logs into a **Prescriptive Analytics Engine**. Instead of merely reporting *what* happened, it identifies *where* the government system is failing to capture citizens and suggests *what should be done*. By isolating demographic outliers (like the low child enrolment in Meghalaya), it allows the Ministry to shift from a 'blanket distribution' strategy to a 'surgical intervention' strategy.

**Actionable Operational Protocols (SOPs):**
Based on the insights generated by this module, the following actions are recommended:
* **Resource Reallocation:** Immediately reroute 30% of mobile enrolment kits from high-saturation states (like Bihar/UP) to the identified 'Red Zone' districts in Meghalaya (e.g., South Garo Hills).
* **Inter-Ministerial Convergence:** Share the 'District-wise Child Deficit' list with the Ministry of Women and Child Development (MWCD). Anganwadi workers in these specific pincodes must be incentivized to bring children to camps.
* **Camp Scheduling Optimization:** Use the Temporal Trends analysis to avoid scheduling camps during periods of historically low turnout, or to target specific demographics during their peak availability (e.g., weekends for school-age children).

---

### **2. Statistical Analysis Methodologies Explained**
To derive these actionable insights, this dashboard utilizes a layered statistical approach. Here is how each method is applied to the Aadhar dataset:

#### **A. Univariate Analysis (Single Variable)**
* **Definition:** The analysis of a single variable in isolation to describe its distribution, central tendency, and dispersion.
* **Application in this Module:** * **Visual:** The **Demographic Segmentation (Pie Chart)**.
    * **The Insight:** We analyze the 'Age Group' column independently. This establishes the **national baseline composition**. Without this univariate analysis, we wouldn't know that 0-5 enrolments are generally high (~43%) nationwide, making the drop in Meghalaya statistically significant. It answers: *"Who are we enrolling generally?"*

#### **B. Bivariate Analysis (Two Variables)**
* **Definition:** The analysis of the relationship between two variables to determine empirical associations or correlations.
* **Application in this Module:** * **Visual:** The **State-wise Child Enrolment Efficiency (Bar Chart)**.
    * **The Insight:** We plot **'State' (Categorical)** against **'Child Enrolment Proportion' (Numerical)**. This reveals the correlation between specific regions and their efficiency in capturing child enrolments. It allows us to rank states not just by volume (which biases results toward large states like UP) but by *efficiency*, revealing hidden underperformers. It answers: *"Which regions are failing a specific demographic?"*

#### **C. Trivariate Analysis (Three Variables)**
* **Definition:** The simultaneous analysis of three variables to understand complex hierarchical or temporal relationships.
* **Application in this Module:** * **Visual 1: Geospatial Hierarchy (Sunburst Chart).** * *Variables:* State + District + Total Enrolment. 
        * *The Insight:* This shows how district-level contributions (Level 2) aggregate up to state-level volumes (Level 1). It helps identify if a state's poor performance is uniform or caused by a few specific 'black hole' districts.
    * **Visual 2: Temporal Trends (Line Chart).** * *Variables:* Date (Time) + Enrolment Count (Volume) + Age Group (Category).
        * *The Insight:* By intersecting time, volume, and demographics, we can see behavioral patterns. For instance, a spike in 'Age 5-17' specifically during school holidays would be a trivariate insight that neither a simple timeline nor a simple age count could show independently.
""")

st.divider()

# -----------------------------------------------------------------------------
# 4. Control Panel (Relocated to Top Navigation Bar)
# -----------------------------------------------------------------------------
st.markdown("#### 🎛️ Control Panel")

# Using columns to create a horizontal navigation/filter bar
nav_col1, nav_col2 = st.columns(2)

# State Filter - No default selection (shows all by default)
with nav_col1:
    all_states = sorted(df['state'].unique())
    selected_states = st.multiselect(
        "Filter by State", 
        all_states, 
        default=[]
    )

    if not selected_states:
        filtered_df = df
        st.caption("Showing data for ALL states.")
    else:
        filtered_df = df[df['state'].isin(selected_states)]

# Date Filter
with nav_col2:
    min_date = df['date'].min()
    max_date = df['date'].max()

    if pd.notnull(min_date) and pd.notnull(max_date):
        start_date, end_date = st.date_input(
            "Filter by Date Range",
            [min_date, max_date],
            min_value=min_date,
            max_value=max_date
        )
        # Filter by date
        filtered_df = filtered_df[
            (filtered_df['date'] >= pd.to_datetime(start_date)) & 
            (filtered_df['date'] <= pd.to_datetime(end_date))
        ]

st.divider()

# -----------------------------------------------------------------------------
# 5. KPI Metrics (Calculated based on Filters)
# -----------------------------------------------------------------------------
col1, col2, col3, col4 = st.columns(4)

total_enrolments = filtered_df['Total Enrolment'].sum()
# Handle division by zero if filter result is empty
if total_enrolments > 0:
    avg_child_ratio = (filtered_df['age_0_5'].sum() / total_enrolments) * 100
    top_district = filtered_df.groupby('district')['Total Enrolment'].sum().idxmax()
    top_state_vol = filtered_df.groupby('state')['Total Enrolment'].sum().idxmax()
else:
    avg_child_ratio = 0
    top_district = "N/A"
    top_state_vol = "N/A"

col1.metric("Total Records Processed", f"{total_enrolments:,}")
col2.metric("Nat'l Child (0-5) Ratio", f"{avg_child_ratio:.1f}%")
col3.metric("Top District (Volume)", top_district)
col4.metric("Top State (Volume)", top_state_vol)

st.divider()

# -----------------------------------------------------------------------------
# 6. Advanced Visualizations (Tabs)
# -----------------------------------------------------------------------------
tab1, tab2, tab3, tab4 = st.tabs([
    "🗺️ Geospatial Hierarchy", 
    "📊 Demographics Analysis", 
    "📈 Temporal Trends", 
    "📋 Key Findings & Interventions"
])

# --- TAB 1: HIERARCHY ---
with tab1:
    st.subheader("Regional Enrolment Distribution")
    st.markdown("""
    **Visualization Guide:**
    This **Sunburst Chart** provides a hierarchical view of enrolment data. 
    * **Inner Circle:** Represents the State level.
    * **Outer Circle:** Represents the District level.
    * **Interaction:** Click on any State slice to drill down and view only its districts. Click the center to zoom back out.
    * **Utility:** Helps identify which specific districts are driving a state's total volume.
    """)
    
    if not filtered_df.empty:
        # Aggregating for Sunburst
        sunburst_data = filtered_df.groupby(['state', 'district'])['Total Enrolment'].sum().reset_index()
        # Filter for performance
        if len(sunburst_data) > 500:
            sunburst_data = sunburst_data.sort_values('Total Enrolment', ascending=False).head(500)

        fig_sun = px.sunburst(
            sunburst_data, 
            path=['state', 'district'], 
            values='Total Enrolment',
            color='Total Enrolment',
            color_continuous_scale='RdBu',
            title="Enrolment Volume Hierarchy"
        )
        st.plotly_chart(fig_sun, use_container_width=True)
    else:
        st.warning("No data available for the selected filters.")

# --- TAB 2: DEMOGRAPHICS ---
with tab2:
    col_a, col_b = st.columns(2)
    
    with col_a:
        st.subheader("Demographic Segmentation")
        st.markdown("""
        **Visualization Guide:**
        This **Pie Chart** breaks down the total enrolments into three mandatory age categories.
        * **0-5:** Bal Aadhar (Critical focus area).
        * **5-17:** School-age children.
        * **18+:** Adult updates/enrolments.
        """)
        if not filtered_df.empty:
            age_sums = filtered_df[['age_0_5', 'age_5_17', 'age_18_greater']].sum().reset_index()
            age_sums.columns = ['Age Group', 'Count']
            
            fig_pie = px.pie(
                age_sums, 
                values='Count', 
                names='Age Group', 
                hole=0.4,
                color_discrete_sequence=px.colors.sequential.Teal
            )
            st.plotly_chart(fig_pie, use_container_width=True)
        else:
            st.write("No data available.")

    with col_b:
        st.subheader("State-wise Child Enrolment Efficiency")
        st.markdown("""
        **Visualization Guide:**
        This **Bar Chart** ranks states based on the *proportion* of children (0-5) in their total enrolment figures.
        * **Red Bars:** Indicate states with low child enrolment ratios (Needs attention).
        * **Utility:** Allows the Ministry to identify which states are failing to capture new births in the Aadhar ecosystem.
        """)
        if not filtered_df.empty:
            state_stats = filtered_df.groupby('state')[['age_0_5', 'Total Enrolment']].sum().reset_index()
            state_stats['Child_Prop'] = state_stats['age_0_5'] / state_stats['Total Enrolment']
            state_stats = state_stats.sort_values('Child_Prop', ascending=True)

            fig_bar = px.bar(
                state_stats, 
                x='Child_Prop', 
                y='state',
                orientation='h',
                title="Proportion of 0-5 Age Enrolments (Low to High)",
                labels={'Child_Prop': 'Ratio of 0-5 Enrolments', 'state': 'State'},
                color='Child_Prop',
                color_continuous_scale='Reds' 
            )
            st.plotly_chart(fig_bar, use_container_width=True)
        else:
            st.write("No data available.")

# --- TAB 3: TRENDS ---
with tab3:
    st.subheader("Registration Volume Timeline")
    st.markdown("""
    **Visualization Guide:**
    This **Time-Series Line Chart** tracks the daily processing volume for each age group.
    * **Utility:** Useful for monitoring the immediate impact of enrolment camps or identifying operational downtimes (drops in data).
    * **Markers:** Each point represents a single day's aggregated data.
    """)
    if not filtered_df.empty:
        daily_stats = filtered_df.groupby('date')[['age_0_5', 'age_5_17', 'age_18_greater']].sum().reset_index()
        daily_melted = daily_stats.melt(id_vars='date', var_name='Age Group', value_name='Enrolments')
        
        fig_line = px.line(
            daily_melted, 
            x='date', 
            y='Enrolments', 
            color='Age Group',
            markers=True,
            title="Daily Enrolment Activity by Age Category"
        )
        st.plotly_chart(fig_line, use_container_width=True)
    else:
        st.write("No data available.")

# --- TAB 4: STRATEGIC INSIGHTS ---
with tab4:
    st.markdown("## 📌 Policy Intervention Proposal")
    
    st.markdown("""
    **Module Purpose:** This section uses algorithmic analysis to compare regional performance against national benchmarks and propose actionable interventions.
    """)
    
    st.markdown("""
    <div style='background-color: rgba(255, 205, 210, 0.3); padding: 20px; border-radius: 10px; border-left: 5px solid #c62828;'>
        <h4>🚨 Critical Finding: Regional Enrolment Disparity</h4>
        <p>Comparative analysis reveals a significant deficit in <b>0-5 age group enrolments in Meghalaya (~19%)</b> against the national average (~43%). 
        This disparity necessitates immediate administrative action to ensure universal coverage for child welfare schemes.</p>
    </div>
    """, unsafe_allow_html=True)
    
    st.divider()
    
    # Data for the insight
    # Note: We use the full 'df' here to show the comparative insight regardless of filters
    insight_df = df.groupby('state')[['age_0_5', 'Total Enrolment']].sum().reset_index()
    insight_df['Child_Ratio'] = insight_df['age_0_5'] / insight_df['Total Enrolment']
    
    try:
        meghalaya_val = insight_df[insight_df['state'] == 'Meghalaya']['Child_Ratio'].values[0]
        bihar_val = insight_df[insight_df['state'] == 'Bihar']['Child_Ratio'].values[0]
        
        # 1. Gauge Chart Comparison
        col_x, col_y = st.columns(2)
        
        with col_x:
            st.markdown("""
            **Visualization Guide (Gauge Chart):**
            Displays the target state's performance (Meghalaya) relative to a benchmark high-performing state (Bihar). The 'Delta' (arrow) indicates the gap that needs to be bridged.
            """)
            fig_gauge = go.Figure(go.Indicator(
                mode = "gauge+number+delta",
                value = meghalaya_val * 100,
                domain = {'x': [0, 1], 'y': [0, 1]},
                title = {'text': "Meghalaya Child Enrolment %"},
                delta = {'reference': bihar_val * 100, 'increasing': {'color': "green"}, 'decreasing': {'color': "red"}},
                gauge = {
                    'axis': {'range': [None, 60], 'tickwidth': 1, 'tickcolor': "darkblue"},
                    'bar': {'color': "#d32f2f"},
                    'steps': [
                        {'range': [0, 25], 'color': "#ffcdd2"},
                        {'range': [25, 60], 'color': "white"}],
                    'threshold': {
                        'line': {'color': "green", 'width': 4},
                        'thickness': 0.75,
                        'value': bihar_val * 100}}))
            st.plotly_chart(fig_gauge, use_container_width=True)
            st.caption(f"Benchmark: High-Volume State (Bihar) at {bihar_val*100:.1f}%")

        with col_y:
            st.markdown("""
            **Action Plan (Priority List):**
            This table identifies specific districts within the underperforming state that have the lowest enrolment ratios. These are the recommended locations for immediate deployment of mobile enrolment vans.
            """)
            st.subheader("📍 Target Districts for Mobile Units")
            
            meg_df = df[df['state'] == 'Meghalaya']
            meg_dist = meg_df.groupby('district')[['age_0_5', 'Total Enrolment']].sum().reset_index()
            meg_dist['Ratio'] = meg_dist['age_0_5'] / meg_dist['Total Enrolment']
            target_list = meg_dist.sort_values('Ratio').head(5)
            
            st.dataframe(
                target_list.style.format({'Ratio': '{:.2%}'}).background_gradient(subset=['Ratio'], cmap='Reds_r'),
                use_container_width=True
            )
    except IndexError:
        st.error("Insufficient data to generate specific comparative insights.")

# Footer (Simple, no branding)
st.markdown("---")
st.caption("Ministry of Electronics and Information Technology (MeitY) | Confidential Policy Draft | AEMS v1.0")